AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SQS to Lambda to SNS with SAM

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 5
    CodeUri: ./
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        STAGE: !Sub ${Stage}
        REGION: us-east-1

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: API Gateway stage name
  VpcID:
    Type: String
    Description: VPC ID
  Subnet1:
    Type: String
    Description: subnet1
  Subnet2:
    Type: String
    Description: subnet2
  DBUser:
    Type: String
    Default: dev-user
    Description: RDS database username
  DBPassword:
    Type: String
    NoEcho: true
    Description: RDS database password
  DBName:
    Type: String
    Default: postgres
    Description: RDS database name

Resources:
  ReceiverQueue:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ReceiverQueue-${Stage}
      ReceiveMessageWaitTimeSeconds: 0
      MessageRetentionPeriod: 60
      VisibilityTimeout: 30
      DelaySeconds: 0
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5

  DeadLetterQueue:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub DeadLetterQueue-${Stage}
      MessageRetentionPeriod: 1209600 # 14 days
      VisibilityTimeout: 30
      DelaySeconds: 0

  # -------------------------------------#-------------------------------------

  SnsToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ReceiverQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt ReceiverQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref TopicCalledWasMade

  TopicCalledWasMade:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub TopicCalledWasMade-${Stage}
      DisplayName: A Call Has Been Made

  QueueSubscriberToTopic:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref TopicCalledWasMade
      Protocol: sqs
      Endpoint: !GetAtt ReceiverQueue.Arn
      # RawMessageDelivery:

  # LambdaSusbriberToTopic:
  #   Type: AWS::SNS::Subscription
  #   Properties:
  #     TopicArn: !Ref TopicCalledWasMade
  #     Protocol: lambda
  #     Endpoint: !GetAtt ReceiverFunction.Arn
  # DeliveryPolicy:
  # FilterPolicy:
  # RawMessageDelivery:

  # -------------------------------------#-------------------------------------

  ApiGatewayReceiver:
    Type: AWS::Serverless::Api
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub ApiGatewayReceiver-${Stage}
      Description: API Gateway for receiving messages
      StageName: !Sub ${Stage}
      Auth:
        ApiKeyRequired: true
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub ApiKey-${Stage}
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGatewayReceiver
          StageName: !Ref ApiGatewayReceiver.Stage
      Description: API Key for accessing the API

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      Description: Usage plan for the API
      ApiStages:
        - ApiId: !Ref ApiGatewayReceiver
          Stage: !Ref ApiGatewayReceiver.Stage
      Quota:
        Limit: 1000
        Period: MONTH
      Throttle:
        BurstLimit: 20
        RateLimit: 10

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  # -------------------------------------#-------------------------------------

  MessageProcessorFunction:
    FunctionName: !Sub MessageProcessorFunction-${Stage}
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/handlers/sqs-message-processor/index.ts
    Properties:
      Handler: src/handlers/sqs-message-processor/index.handler
      Environment:
        Variables:
          QUEUE_URL: !Ref ReceiverQueue
          DEAD_LETTER_QUEUE_URL: !Ref DeadLetterQueue
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ReceiverQueue.Arn
            BatchSize: 10

  ReceiverFunction:
    FunctionName: !Sub ReceiverFunction-${Stage}
    Type: AWS::Serverless::Function
    memorySize: 128
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/handlers/receiver/index.ts
    Properties:
      Handler: src/handlers/receiver/index.handler
      Environment:
        Variables:
          DB_HOST: !GetAtt rdsDBInstance.Endpoint.Address
          DB_PORT: !GetAtt rdsDBInstance.Endpoint.Port
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          SNS_TOPIC_ARN: !Ref TopicCalledWasMade
      Events:
        ApiKey:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayReceiver
            Path: /
            Method: get
            Auth:
              ApiKeyRequired: true
      Policies:
        - AWSLambdaSQSQueueExecutionRole
        - Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: !Ref TopicCalledWasMade
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - rds:*
              Resource: !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:*
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref Subnet1
          - !Ref Subnet2

  # -------------------------------------#-------------------------------------

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda
      VpcId: !Ref VpcID
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  SNSEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcID
      ServiceName: !Sub com.amazonaws.${AWS::Region}.sns
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup
      PrivateDnsEnabled: true

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS
      VpcId: !Ref VpcID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSecurityGroup

  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BackupRetentionPeriod: 0
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      DBInstanceIdentifier: postgres-db
      DBName: postgres
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      # DBSecurityGroups:
      #   - !Ref RDSSecurityGroup
      Engine: postgres
      EngineVersion: "17.5"
      MasterUsername: !Sub DBUser
      MasterUserPassword: !Sub DBPassword
      PubliclyAccessible: false
      StorageEncrypted: false

Outputs:
  SqsQueueArn:
    Description: ARN of the SQS Queue
    Value: !GetAtt ReceiverQueue.Arn
  SnsTopicArn:
    Description: ARN of the SNS Topic
    Value: !Ref TopicCalledWasMade
  MessageProcessorFunctionArn:
    Description: ARN of the MessageProcessorFunction Function
    Value: !GetAtt MessageProcessorFunction.Arn
  ReceiverFunctionArn:
    Description: ARN of the ReceiverFunction Function
    Value: !GetAtt ReceiverFunction.Arn
  ApiKey:
    Description: API Key for accessing the API
    Value: !Ref ApiKey
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGatewayReceiver}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
